### ISSUE TITLE
collecting data from several folders don't work

### ISSUE THREAD

**Issue by avkonst** [metrixplusplus/metrixplusplus#2]
(moved from sourceforge)

collecting data from several folders don't work : only the first folder is taken in account.
Please see the attached patch proposal
Thank you for your good work !

Proposed patch
[collect.zip](https://github.com/metrixplusplus/metrixplusplus/files/3036877/collect.zip)

**Comment by unrzn0** [comment]
Just started using metrix++, and collecting over several folders seems to have worked for me using wildcards (here on macOS), e.g. 
`python2.7 metrix++.py collect  --std.code.complexity.cyclomatic -- src/lib*/*.[c,h]`

Having this built-in is however preferred, thus I'd vote also for the above patch.

**Comment by avkonst** [comment]
@unrzn0 , thanks for the tip. As I mentioned in the other ticket, would you like to contribute?

**Comment by prozessorkern** [comment]
I just took a look at this one.
As far as I can see the issue was fixed in commit 7ccd343ca67511775cbece79719b074c8b43eb2d
Before this commit only the first directory/file was processed.
Now this seems to work fine (you can pass a list of directories or files and the specified files are processed)

Furthermore the proposed patch to collect.py has already been applied years ago in commit 86fba228f8d788c860b7fc288ea36dd98f6cbcf6

A problem I see with this implementation is that it parses not only file paths but directory and file paths and stops the recursive load of subdirectories and files if the directory is not included by any rule.
So your rules not only have to match the files you want to collect data from, but every intermediate directory on the way...

Was this really the intention of this option?

I'd suggest (and implement) these changes:
1. only apply the include rules on files, directories (so you can write rules to include the files you want out of the directories you have specified, or every file below the working dir if no directory is given)
2. change the rules to be inclusive instead of being exclusive - so you can include more files by adding new rules. Right now every rule has to match every file(and directory) that shall be processed.

What is your opinion?

**Comment by avkonst** [comment]
Shall we go with glob patern like .gitignore content has got?

**Comment by prozessorkern** [comment]
I don't think global pattern will make a big difference.
You could only exclude files which are not parsable by default. This is already given if there is no language plugin for a file extension.
I would just try to make the --include-files option a bit more intuitive and useful.

I will implement this and send you a pull request, so we can decide if it improves this issue.

**Comment by avkonst** [comment]
Thanks for contributing.
