### ISSUE TITLE
Excluding folders

### ISSUE THREAD

**Issue by christianmalek** [metrixplusplus/metrixplusplus#57]
Hi,

I have some issues with symbolic links and that's the reason I want to exclude these folders from collecting.

The folder I want to exclude starts with `connectedhomeip/thirdparty`. The project folder I want to analyse is `./connectedhomeip`. Because of this I executed the command (Ubuntu 22.04 LTS, Python 3.10):

`python3 ~/metrixplusplus/metrix++.py  collect --std.code.lines.code --std.code.complexity.cyclomatic --exclude-files=".*\/third_party\/.*"  -- ./connectedhomeip`

Is there any feedback if the exclusion works? It looks like the script still processes the files in the excluded folder. I assume this because the processing of individual files in this folder takes way too long.

**Comment by huornlmj** [comment]
+1 on excluding or ignoring sym links.  I keep getting Tracebacks due to symlinks.

**Comment by prozessorkern** [comment]
You are right - the current implementation just checks the basename of a file.
You should be able to exclude a directoy/symlink by name - in your example `--exclude-files="third_party"` should work, but will exclude all other directories called third_party.

I will add an info log for the exclusion to be able to detect those issues.

I had issues with this myself and ended up passing an explicit list of files to metrix from my buildsystem.
...excluding directories should be possible though.

I will add a --exclude-directories option for this purpose.

**Comment by huornlmj** [comment]
@prozessorkern I don't think it's a exclude-directories type thing.  Instead, Matrix++ should have a switch that disables following or including symlinks wherever they may be.

**Comment by prozessorkern** [comment]
@huornlmj  - Okay, I get your use case. But there should be no Issue using symlinks with metrix.
If you do not want to analyse those sources you can exclude them using the new --exclude-directories.

I just tested metrix following symlinks on linux without noticing any Issue.
As different operating systems handle symlinks a bit differently I would rather not add a symlink filter feature - if you do not want to analyze certain parts of your working directory either include all sources to be analyzed explicitly, or use the recursive feature and exclude stuff you do want to skip.

Can you share the tracebacks caused by symlinks + some more details (in another Issue) - maybe there is a bug I can address instead.

**Comment by huornlmj** [comment]
Exclude dirs is not the solution I'm referring to here.  Telling metrixplusplus to simply not follow symlinks if they are found would have been the solution.  I don't have the traceback error any more since I moved to a different CC measuring tool in the meantime.
